import "./globals.css";
import { Inter } from "next/font/google";
import Navbar from "../components/Navbar";
import Footer from "../components/Footer";
import ScrollTotopButton from "../components/ScrollTotopButton";
import Map from "../components/Map";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Jeep electric scooters",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Navbar />
        {children}
        <ScrollTotopButton />
        <Footer />
      </body>
    </html>
  );
}
